export const ADDRECIPETOFAVORITES = "ADDRECIPETOFAVORITES";
export const TESTCASE2 = "TESTCASE2";
export const REMOVERECIPEFROMFAVORITES = "REMOVERECIPEFROMFAVORITES";
export const INDIVIDUALRECIPEDATA = "INDIVIDUALRECIPEDATA";
