export const ADDRECIPETOFAVORITES = "ADDRECIPETOFAVORITES";
export const TESTCASE2 = "TESTCASE2";
export const REMOVERECIPEFROMFAVORITES = "REMOVERECIPEFROMFAVORITES";
export const INDIVIDUALRECIPEDATA = "INDIVIDUALRECIPEDATA";
export const ADDRECIPETOLIST = "ADDRECIPETOLIST";
export const REMOVERECIPEFROMLIST = "REMOVERECIPEFROMLIST";
export const HOMEPAGEBROWSE = "HOMEPAGEBROWSE";
